---
deployment:
  tasks:
    - export DEPLOYPATH=/home/suhadipc/public_html/web_sikado/
    - /bin/rm -rf $DEPLOYPATH/app
    - /bin/rm -rf $DEPLOYPATH/bootstrap
    - /bin/rm -rf $DEPLOYPATH/config
    - /bin/rm -rf $DEPLOYPATH/database
    - /bin/rm -rf $DEPLOYPATH/resources
    - /bin/rm -rf $DEPLOYPATH/routes
    - /bin/rm -rf $DEPLOYPATH/lang
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R lang $DEPLOYPATH
    - /bin/cp -R public/. $DEPLOYPATH/public/
    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/storage/framework/cache
    - /bin/mkdir -p $DEPLOYPATH/storage/framework/sessions
    - /bin/mkdir -p $DEPLOYPATH/storage/framework/views
    - /bin/mkdir -p $DEPLOYPATH/storage/logs
    - /bin/mkdir -p $DEPLOYPATH/bootstrap/cache
    - /bin/chmod -R 775 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache